#spring:
#  application:
#    name: mall-gateway
# 注册中心
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
        client-ip: 192.168.0.102
server:
  port: 8070
management:
  endpoints:
    web:
      exposure:
        include: '*'
