#spring:
#  application:
#    name: mall-gateway
# 注册中心
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
server:
  port: 8070

