server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-auth
  thymeleaf:
    cache: false # 关闭缓存，不然热部署不起作用
  redis:
    port: 6379
    host: 127.0.0.1