server:
  port: 8092
#  servlet:
#    session:
#      timeout: 30 # Session timeout. If a duration suffix is not specified, seconds is used.
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-auth
  thymeleaf:
    cache: false # 关闭缓存，不然热部署不起作用
  redis:
    port: 6379
    host: 127.0.0.1
  session:
    store-type: redis # Session store type
    redis:
#      flush-mode: on_save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.