server:
  port: 8093
  servlet:
    session:
      timeout: 30m
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-cart
  thymeleaf:
    cache: false # 关闭缓存，不然热部署不起作用
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    redis:
      namespace: spring:session
    store-type: redis