spring:
#  application:
#    name: mall-product
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/mall-pms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false # 关闭thymeleaf缓存
  redis:
    host: 127.0.0.1
    port: 6379
# ??????????
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto   #????
#      logic-delete-field: showStatus
#      logic-delete-value: 0
#      logic-not-delete-value: 1
server:
  port: 8040

