server:
  port: 8096
  servlet:
    session:
      timeout: 30m
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719
        client-ip: 192.168.0.102
  application:
    name: mall-seckill
  thymeleaf:
    cache: false # 关闭缓存，不然热部署不起作用
  session:
    store-type: redis
    redis:
      namespace: spring:session
# 定时任务异步执行 线程配置
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
  redis:
    host: 127.0.0.1
    port: 6379
# RocketMQ的相关信息
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: seckill-order-producer
  consumer:
    group: seckill-order-consumer
management:
  endpoints:
    web:
      exposure:
        include: '*'
