server:
  port: 8096
  servlet:
    session:
      timeout: 30m
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-seckill
  thymeleaf:
    cache: false # 关闭缓存，不然热部署不起作用
  session:
    store-type: redis
    redis:
      namespace: spring:session
