spring:
  application:
    name: mall-order
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/mall-oms?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719
        client-ip: 192.168.0.102
  session:
    store-type: redis
    redis:
      namespace: spring:session
  redis:
    port: 6379
    host: 127.0.0.1
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto   #主键自增
server:
  port: 8030
  servlet:
    session:
      timeout: 30m

user:
  userName: yyqx
  age: 24
rocketmq:
  name-server: 192.168.0.102:9876
  producer:
    group: order-producer
  consumer:
    group: order-consumer

management:
  endpoints:
    web:
      exposure:
        include: '*'